Itg tests confluent (#3)
* modify local run, and add kafdrop

* Added kcontainer-quickstart-ocp script (#142)

Signed-off-by: Rick Osowski <rosowski@gmail.com>

* Updating Strimzi Operator version per https://github.com/ibm-cloud-architecture/refarch-kc/issues/143

Signed-off-by: Rick Osowski <rosowski@gmail.com>

* Made quickstart script executable (#145)

Signed-off-by: Rick Osowski <rosowski@gmail.com>

* Made quickstart script executable (#146)

Signed-off-by: Rick Osowski <rosowski@gmail.com>

* Added OCP version detection for Strimzi installation (#147)

* Made quickstart script executable

Signed-off-by: Rick Osowski <rosowski@gmail.com>

* Added OCP version detection for Strimzi installation

Signed-off-by: Rick Osowski <rosowski@gmail.com>

* adding --skip-login flag for openLabs (#148)

Co-authored-by: Jesús Almaraz Hernández <jesusalmarazhernandez@jesuss-mbp.home>

* adding openlabs to the quickstart (#149)

Co-authored-by: Jesús Almaraz Hernández <jesusalmarazhernandez@jesuss-mbp.home>

* use lab 6 of IBM OpenLabs (#152)

Co-authored-by: Jesús Almaraz Hernández <jesusalmarazhernandez@jesuss-mbp.home>

* Broke quickstart into tabbed pages (#153)

Signed-off-by: Rick Osowski <rosowski@gmail.com>

* Updated wait times for quickstart script (#154)

Signed-off-by: Rick Osowski <rosowski@gmail.com>

* Updating itgtests for Confluent support

Signed-off-by: Rick Osowski <rosowski@gmail.com>

* quickstart refactoring (#155)

Co-authored-by: Jesús Almaraz Hernández <jesusalmarazhernandez@jesuss-mbp.home>

* fix for new curl commands

* updated python container reference to quay.io

Signed-off-by: Rick Osowski <rosowski@gmail.com>

* CONFLUENT ITGTESTS SUPPORT

* Minor wording updates for Confluent ITGTESTS support

Signed-off-by: Rick Osowski <rosowski@gmail.com>

Co-authored-by: Jerome Boyer <boyerje@us.ibm.com>
Co-authored-by: Jesus Almaraz <almarazj@ie.ibm.com>
Co-authored-by: Jesús Almaraz Hernández <jesusalmarazhernandez@jesuss-mbp.home>
Co-authored-by: Jesús Almaraz Hernández <jesusalmarazhernandez@192.168.1.135>
Co-authored-by: Hemankita Perabathini <phemankita@gmail.com>

diff --git a/itg-tests/es-it/ReeferItgTests.yaml b/itg-tests/es-it/ReeferItgTests.yaml
--- a/itg-tests/es-it/ReeferItgTests.yaml
+++ b/itg-tests/es-it/ReeferItgTests.yaml
@@ -9,24 +9,12 @@ spec:
     spec:
       containers:
       - name: ibmcase-python
-        image: ibmcase/kcontainer-python:itgtests
+        image: quay.io/ibmcase/kcontainer-python:itgtests
         imagePullPolicy: Always
         command:
         - /bin/bash
         - -c
         - |
-              # Understand what environment we are executing against
-              if [ -z "$KAFKA_USER" ]; then
-                KAFKA_ENV="LOCAL"
-              elif [ "$KAFKA_USER" == "token" ]; then
-                KAFKA_ENV="IBMCLOUD"
-              else
-                KAFKA_ENV="OCP"
-              fi
-
-              # Export KAFKA_ENV since it is used by the test cases
-              export KAFKA_ENV=${KAFKA_ENV}
-
               # Obfuscate KAFKA_PASSWORD
               if [ "`echo -n ${KAFKA_PASSWORD} | wc -c`" -gt 3 ]; then
                 FIRST_CH=${KAFKA_PASSWORD:0:1}
@@ -42,9 +30,10 @@ spec:
               echo
               echo "Executing integrations tests from branch $BRANCH of $GITHUB_REPO"
               echo "Kafka Brokers: $KAFKA_BROKERS"
+              echo "Kafka Security protocol: $SECURITY_PROTOCOL"
+              echo "Kafka SASL mechanism: $SASL_MECHANISM"
               echo "Kafka user: $KAFKA_USER"
               echo "Kafka password: $OBFUSCATED_PASSWORD"
-              echo "Kafka Env: $KAFKA_ENV"
               echo "Orders topic name: $ITGTESTS_ORDERS_TOPIC"
               echo "Order Command topic name: $ITGTESTS_ORDER_COMMANDS_TOPIC"
               echo "Containers topic name: $ITGTESTS_CONTAINERS_TOPIC"
@@ -57,17 +46,27 @@ spec:
                 exit 1
               fi
 
-              if [ "$KAFKA_ENV" != "LOCAL" -a -z "$KAFKA_PASSWORD" ]; then
-                echo "[ERROR] - KAFKA_PASSWORD environment variable must be set."
-                exit 1
+              # Check that a Kafka user and password are provided if there is authentication set up
+              if [ "$SECURITY_PROTOCOL" == "SASL_PLAINTEXT" ] || [ "$SECURITY_PROTOCOL" == "SASL_SSL" ]; then
+                if [ -z "$KAFKA_USER" ]; then
+                  echo "[ERROR] - A Kafka user was not provided."
+                  exit 1
+                fi
+                if [ -z "$KAFKA_PASSWORD" ]; then
+                  echo "[ERROR] - A Kafka password was not provided."
+                  exit 1
+                fi
               fi
 
-              # Check that if we are using IBM Event Streams on prem, we are providing the PEM certificate to connect to it.
-              if [ "$KAFKA_ENV" == "OCP" ]  && [ ! -f "$PEM_CERT" ]; then
-                echo "[ERROR] - The PEM certificate to connect to IBM Event Streams on premise could not be found."
-                echo "[ERROR] - Please make sure you have created the kubernetes secret with the PEM certificate and"
-                echo "[ERROR] - you have uncommented the mount of such secret in the integration tests yaml file."
-                exit 1
+              # Ideally, we would check here if SECURITY_PROTOCOL is SSL or SASL_SSL which are the two security protocols that use SSL certs.
+              # However, IBM Event Streams on IBM Cloud uses SASL_SSL but there is no need for a certificate.
+              # Hence, we can only warn that
+              if [ "$SECURITY_PROTOCOL" == "SSL" ] || [ "$SECURITY_PROTOCOL" == "SASL_SSL" ]; then
+                if [ ! -f "$PEM_CERT" ]; then
+                  echo "[WARNING] - A PEM certificate could not be found. This might be necessary to establish the appropriate secured communication to the Kafka cluster."
+                  echo "[WARNING] - If it is needed, make sure you have created a Kubernetes Secret named 'kafka-truststore-pem' with the PEM certificate"
+                  echo "[WARNING] - as referenced in the Integration Tests YAML file."
+                fi
               fi
 
               # Creating the working directory
@@ -143,6 +142,39 @@ spec:
               echo "-- END --"
               echo "---------"
         env:
+        # Event Streams Kafka brokers. You MUST create a configmap in advance with the brokers information:
+        # oc create configmap kafka-brokers --from-literal=brokers='<replace with comma-separated list of brokers>' -n <namespace>
+        # You can find the list of brokers either in the Event Streams UI or when you login through the CLI: cloudctl es init
+        - name: KAFKA_BROKERS
+          valueFrom:
+            configMapKeyRef:
+              name: "kafka-brokers"
+              key: brokers
+        # Your Event Streams credentials. You can find it in the Event Streams UI on the connect to this cluster link
+        # You MUST create this secret in advance with the Event Streams username and password:
+        # kubectl create secret generic eventstreams-cred --from-literal=username='<replace with kafka username>' --from-literal=password='<replace with kafka password>'
+        - name: KAFKA_USER
+          valueFrom:
+            secretKeyRef:
+              name: "kafka-credentials"
+              key: username
+              optional: true
+        - name: KAFKA_PASSWORD
+          valueFrom:
+            secretKeyRef:
+              name: "kafka-credentials"
+              key: password
+              optional: true
+        # Location of your Event Streams pem certificate for ssl connections. You MUST download it in advance.
+        # This can be downloaded from the Event Streams UI.
+        - name: PEM_CERT
+          value: "/tmp/certs/kafka-cert.pem"
+        # TODO Documentation TBD
+        - name: SASL_MECHANISM
+          value: "PLAIN"
+        # TODO Documentation TBD
+        - name: SECURITY_PROTOCOL
+          value: "SASL_SSL"
         # Your working directory within the container
         - name: WORKING_DIR
           value: "/tmp/github"
@@ -158,29 +190,6 @@ spec:
         # Location of the integration tests folder within the repository
         - name: ITGTESTS_LOCATION
           value: "itg-tests/es-it"
-        # Event Streams Kafka brokers. You MUST create a configmap in advance with the brokers information:
-        # oc create configmap kafka-brokers --from-literal=brokers='<replace with comma-separated list of brokers>' -n <namespace>
-        # You can find the list of brokers either in the Event Streams UI or when you login through the CLI: cloudctl es init
-        - name: KAFKA_BROKERS
-          valueFrom:
-            configMapKeyRef:
-              name: "kafka-brokers"
-              key: brokers
-        # Your Event Streams credentials. You can find it in the Event Streams UI on the connect to this cluster link
-        # You MUST create this secret in advance with the Event Streams username and password:
-        # kubectl create secret generic eventstreams-cred --from-literal=username='<replace with kafka username>' --from-literal=password='<replace with kafka password>'
-        - name: KAFKA_USER
-          valueFrom:
-            secretKeyRef:
-              name: "eventstreams-cred"
-              key: username
-              optional: true
-        - name: KAFKA_PASSWORD
-          valueFrom:
-            secretKeyRef:
-              name: "eventstreams-cred"
-              key: password
-              optional: true
         # Order command microservice's service name
         - name: ORDER_CMD_MS
           value: "order-command-ms:9080"
@@ -228,10 +237,6 @@ spec:
             configMapKeyRef:
               name: kafka-topics
               key: containerAnomalyDeadTopic
-        # Location of your Event Streams pem certificate for ssl connections. You MUST download it in advance.
-        # This can be downloaded from the Event Streams UI.
-        - name: PEM_CERT
-          value: "/tmp/certs/es-cert.pem"
         # Location where the Event Streams pem certificate contained in the eventstreams-pem-file secret will be loaded to.
         volumeMounts:
         - mountPath: "/tmp/certs"
@@ -241,7 +246,7 @@ spec:
          # Then create the secret: oc create secret generic eventstreams-cert-pem --from-file=es-cert.pem=<LOCATION_OF_YOUR_EVENT_STREAMS_PEM_CERTIFICATE> -n <namespace>
          - name: eventstreams-pem-file
            secret:
-             secretName: "eventstreams-cert-pem"
+             secretName: "kafka-truststore-pem"
              optional: true
       restartPolicy: Never
   backoffLimit: 0
